require("basic")

require("keybindings")

require("plugins")

require("colorscheme")

require("plugin-config/nvim-bufferline")
require("plugin-config/nvim-tree")
require("plugin-config/nvim-treesitter")
require("plugin-config/nvim-lualine")
require("plugin-config/nvim-gitsigns")
require("plugin-config/toggleterm")
require("plugin-config/indent-blankline")
require("plugin-config/nvim-lastplace")
require("plugin-config/lsp")
require("plugin-config/lspsaga")
require("plugin-config/nvim-cmp")
require("plugin-config/nvim-lint")
require("plugin-config/neoformat")
require("plugin-config/which-key")
require("plugin-config/diffview")
require("plugin-config/telescope")
require("plugin-config/symbols-outline")
require("plugin-config/nnn")
require("plugin-config/fidget")
require("plugin-config/stylua")
require("plugin-config/dap")
require("plugin-config/cmake")
